/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugAvaliarRouteImport } from './routes/$slug.avaliar'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardArtesRouteImport } from './routes/dashboard.artes'
import { Route as DashboardAvaliacoesRouteImport } from './routes/dashboard.avaliacoes'
import { Route as DashboardClientesRouteImport } from './routes/dashboard.clientes'
import { Route as DashboardEstrategiasRouteImport } from './routes/dashboard.estrategias'
import { Route as DashboardVitrineRouteImport } from './routes/dashboard.vitrine'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAvaliarRoute = SlugAvaliarRouteImport.update({
  id: '/$slug/avaliar',
  path: '/$slug/avaliar',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArtesRoute = DashboardArtesRouteImport.update({
  id: '/artes',
  path: '/artes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAvaliacoesRoute = DashboardAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesRoute = DashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEstrategiasRoute = DashboardEstrategiasRouteImport.update({
  id: '/estrategias',
  path: '/estrategias',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVitrineRoute = DashboardVitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => DashboardRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/$slug/avaliar': typeof SlugAvaliarRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/artes': typeof DashboardArtesRoute
  '/dashboard/avaliacoes': typeof DashboardAvaliacoesRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/estrategias': typeof DashboardEstrategiasRoute
  '/dashboard/vitrine': typeof DashboardVitrineRoute
  '/$slug/': typeof SlugIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/$slug/avaliar': typeof SlugAvaliarRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/artes': typeof DashboardArtesRoute
  '/dashboard/avaliacoes': typeof DashboardAvaliacoesRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/estrategias': typeof DashboardEstrategiasRoute
  '/dashboard/vitrine': typeof DashboardVitrineRoute
  '/$slug': typeof SlugIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/$slug/avaliar': typeof SlugAvaliarRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/artes': typeof DashboardArtesRoute
  '/dashboard/avaliacoes': typeof DashboardAvaliacoesRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/estrategias': typeof DashboardEstrategiasRoute
  '/dashboard/vitrine': typeof DashboardVitrineRoute
  '/$slug/': typeof SlugIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/mcp'
    | '/$slug/avaliar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/artes'
    | '/dashboard/avaliacoes'
    | '/dashboard/clientes'
    | '/dashboard/estrategias'
    | '/dashboard/vitrine'
    | '/$slug/'
    | '/dashboard/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/$slug/avaliar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/artes'
    | '/dashboard/avaliacoes'
    | '/dashboard/clientes'
    | '/dashboard/estrategias'
    | '/dashboard/vitrine'
    | '/$slug'
    | '/dashboard'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/mcp'
    | '/$slug/avaliar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/artes'
    | '/dashboard/avaliacoes'
    | '/dashboard/clientes'
    | '/dashboard/estrategias'
    | '/dashboard/vitrine'
    | '/$slug/'
    | '/dashboard/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SlugAvaliarRoute: typeof SlugAvaliarRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  SlugIndexRoute: typeof SlugIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/avaliar': {
      id: '/$slug/avaliar'
      path: '/$slug/avaliar'
      fullPath: '/$slug/avaliar'
      preLoaderRoute: typeof SlugAvaliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/artes': {
      id: '/dashboard/artes'
      path: '/artes'
      fullPath: '/dashboard/artes'
      preLoaderRoute: typeof DashboardArtesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/avaliacoes': {
      id: '/dashboard/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/dashboard/avaliacoes'
      preLoaderRoute: typeof DashboardAvaliacoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/estrategias': {
      id: '/dashboard/estrategias'
      path: '/estrategias'
      fullPath: '/dashboard/estrategias'
      preLoaderRoute: typeof DashboardEstrategiasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vitrine': {
      id: '/dashboard/vitrine'
      path: '/vitrine'
      fullPath: '/dashboard/vitrine'
      preLoaderRoute: typeof DashboardVitrineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardArtesRoute: typeof DashboardArtesRoute
  DashboardAvaliacoesRoute: typeof DashboardAvaliacoesRoute
  DashboardClientesRoute: typeof DashboardClientesRoute
  DashboardEstrategiasRoute: typeof DashboardEstrategiasRoute
  DashboardVitrineRoute: typeof DashboardVitrineRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardArtesRoute: DashboardArtesRoute,
  DashboardAvaliacoesRoute: DashboardAvaliacoesRoute,
  DashboardClientesRoute: DashboardClientesRoute,
  DashboardEstrategiasRoute: DashboardEstrategiasRoute,
  DashboardVitrineRoute: DashboardVitrineRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SlugAvaliarRoute: SlugAvaliarRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  SlugIndexRoute: SlugIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
